name: Deploy Lambda Function

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli --upgrade

    - name: Deploy Lambda function
      run: |
        aws lambda create-function \
          --function-name atul-lambda1 \
          --runtime python3.8 \
          --handler lambda_function.lambda_handler \
          --role arn:aws:iam::123456789012:role/lambda-role \
          --zip-file fileb://lambda_function.zip
